Fix reification of constructor RHS
The primary constructor body is now `Block(Nil, Unit)` (no more pending super)
This caused a problem because SyntacticBlock first flattens it to `Unit`,
and then SyntacticDefDef panicked and try to turn it into a block, creatively
turning it into `Block(Unit, Unit)`

(I'm using `Unit` as short for the tree representing `()`).

ok  9 - pos/t8781
ok 11 - pos/t8934a
ok 12 - pos/t9392
ok 13 - pos/byname-implicits-32

TODO in pos/:
?!  7 - pos/t3048.scala                           [caught NoSuchElementException - key not found: <$anon: Function0>]

?!  8 - pos/t5384.scala                           [caught IllegalArgumentException - Could not find proxy for x$1: String in List(value x$1, method apply, <$anon: Function1>, value x$2, constructor B1Lam, class B1Lam, package <empty>, package <root>) (currentOwner= method apply )]
error: key not found: <$anon: Function0>

!! 10 - pos/t7046-2                               [compilation failed with 1 errors]

Test_2.scala:9: error: constructor definition not allowed here
case class B(val b: Test.x.type)
           ^
one error found